-- Create team_chat table
create table if not exists team_chat (
  id bigint primary key generated by default as identity,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content text not null,
  sender_email text not null,
  sender_name text not null
);

-- Enable row level security (RLS)
alter table team_chat enable row level security;

-- Create policy to allow authenticated users to read all messages
create policy "Allow authenticated users to read messages"
  on team_chat for select
  to authenticated
  using (true);

-- Create policy to allow authenticated users to insert their own messages
create policy "Allow authenticated users to insert messages"
  on team_chat for insert
  to authenticated
  with check (true);

-- Create realtime subscription
alter publication supabase_realtime add table team_chat;
